#!/usr/bin/env python3
"""Keep the project-guide base block and conventions copy current.

Plan mode (the default) only reads. It prints one row per repository under the
projects root: name, state, action, reason.

  sync.py --root <projects_root> [--worktrees-dir DIR] [--only a,b] [--skip a,b]
          [--apply | --commit | --push] [--json]
  sync.py --repo <path> --add [--copy-only] [--worktrees-dir DIR] [--json]

--apply writes the block and the copy where the action is "update". --commit
also commits exactly those two paths. --push also pushes the default branch to
origin; when origin refuses, it pushes the commit to a review branch instead.
--repo --add places the block and the copy in one folder and never commits.

Standard library only; Python 3.9 or later.
"""
import argparse
import glob
import json
import os
import re
import subprocess
import sys

PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = "https://github.com/rschlek/project-guide"
START = "<!-- project-guide:base start"
END = "<!-- project-guide:base end -->"
START_RE = re.compile(r"<!-- project-guide:base start \(([^)]*)\) -->")
HEADER_RE = re.compile(r"^> Copied from project-guide (\S+) \(" + re.escape(URL) + r"\)\.")
HEADER = ("> Copied from project-guide {v} (" + URL + "). Do not edit this file here; "
          "it is replaced whole when the standard updates.")
AGENTS = "AGENTS.md"
COPY = "docs/project-conventions.md"
BOM = b"\xef\xbb\xbf"
ENV = dict(os.environ, GIT_OPTIONAL_LOCKS="0")
MESSAGE = "Update the project-guide base block and conventions copy ({v})"


class InternalError(Exception):
    pass


def ver(v):
    try:
        return tuple(int(x) for x in v.split("."))
    except (ValueError, AttributeError):
        return None


def newer(v, std):
    t = ver(v)
    return t is not None and t > ver(std)


def git(repo, *args):
    r = subprocess.run(["git", "-C", repo] + list(args), capture_output=True, env=ENV)
    return r.returncode, r.stdout.decode("utf-8", "replace"), r.stderr.decode("utf-8", "replace")


def git_ok(repo, *args):
    rc, out, err = git(repo, *args)
    if rc != 0:
        raise InternalError("git %s failed: %s" % (" ".join(args), last_line(err)))
    return out


def last_line(text):
    lines = [x for x in text.strip().splitlines() if x.strip()]
    return lines[-1].strip() if lines else "no output"


def load(path):
    """Return (text with original line endings, has BOM, uses CRLF)."""
    with open(path, "rb") as f:
        raw = f.read()
    bom = raw.startswith(BOM)
    text = raw[3:].decode("utf-8") if bom else raw.decode("utf-8")
    crlf = text.count("\r\n")
    return text, bom, crlf > text.count("\n") - crlf


def encode(text, bom):
    data = text.encode("utf-8")
    return BOM + data if bom else data


class Standard:
    def __init__(self, worktrees_dir):
        with open(os.path.join(PLUGIN_ROOT, "template", "AGENTS.md"), "rb") as f:
            tpl = f.read().decode("utf-8").replace("\r\n", "\n")
        lines = tpl.split("\n")
        s = [i for i, x in enumerate(lines) if x.startswith(START)]
        e = [i for i, x in enumerate(lines) if x.startswith(END)]
        m = START_RE.match(lines[s[0]]) if len(s) == 1 else None
        if len(e) != 1 or not m or e[0] < s[0] or ver(m.group(1)) is None:
            raise InternalError("template/AGENTS.md has no valid versioned base block")
        self.version = m.group(1)
        wt = worktrees_dir.strip("/\\")
        self.block = [x.replace("<worktrees_dir>", wt) for x in lines[s[0]:e[0] + 1]]
        self.agents_new = tpl.replace("<worktrees_dir>", wt)
        with open(os.path.join(PLUGIN_ROOT, "references", "conventions.md"), "rb") as f:
            conv = f.read().decode("utf-8").replace("\r\n", "\n")
        self.copy = HEADER.format(v=self.version) + "\n\n" + conv
        if "<version>" in "\n".join(self.block) or "<worktrees_dir>" in self.agents_new:
            raise InternalError("a placeholder remains in the standard block")


def block_info(text):
    """None when there is no block, 'malformed', or (start, end, version)."""
    lines = text.split("\n")
    s = [i for i, x in enumerate(lines) if START in x]
    e = [i for i, x in enumerate(lines) if END in x]
    if not s and not e:
        return None
    if len(s) != 1 or len(e) != 1 or e[0] < s[0] or not START_RE.search(lines[s[0]]):
        return "malformed"
    return s[0], e[0], START_RE.search(lines[s[0]]).group(1)


def new_agents_text(text, crlf, info, std):
    """AGENTS.md text with the standard block; every other line byte-for-byte unchanged."""
    lines = text.split("\n")  # with CRLF, each line keeps its own trailing "\r"
    cr = "\r" if crlf else ""
    block = [x + cr for x in std.block]
    if info is not None:
        s, e, _ = info
        return "\n".join(lines[:s] + block + lines[e + 1:])
    heading, fence = None, False
    for i, x in enumerate(lines):
        if re.match(r"^\s{0,3}(```|~~~)", x):
            fence = not fence
        elif not fence and re.match(r"^#{1,6}(\s|$)", x.rstrip("\r")):
            heading = i
            break
    if heading is None:
        pos, ins = 0, block + [cr]
    elif heading + 1 < len(lines) and lines[heading + 1].strip() == "":
        pos, ins = heading + 2, block + [cr]
    else:
        pos, ins = heading + 1, [cr] + block + [cr]
    return "\n".join(lines[:pos] + ins + lines[pos:])


def status_lines(path):
    out = git_ok(path, "status", "--porcelain", "--untracked-files=all")
    return set(x for x in out.split("\n") if x)  # never strip: column 1 may be a space


def is_ignored(path, rel):
    return git(path, "check-ignore", "-q", "--", rel)[0] == 0


def examine(path, std, add=False, copy_only=False):
    """Classify one folder. Returns a row dict; row['_writes'] maps rel path to bytes."""
    row = {"name": "", "path": path, "state": "", "action": "none", "reason": "",
           "_writes": {}, "_commit": [], "_git": os.path.isdir(os.path.join(path, ".git"))}
    in_git = row["_git"]
    ag_path = os.path.join(path, AGENTS)
    cp_path = os.path.join(path, *COPY.split("/"))
    copy_ignored = in_git and is_ignored(path, COPY)
    notes = []

    ag = load(ag_path) if os.path.isfile(ag_path) else None
    binfo = block_info(ag[0]) if ag else None
    cp, cver, cforeign = None, None, False
    if os.path.isfile(cp_path):
        try:
            cp = load(cp_path)
            m = HEADER_RE.match(cp[0].split("\n", 1)[0])
            cver = m.group(1) if m else None
            cforeign = not m
        except UnicodeDecodeError:
            cforeign = True
    bver = binfo[2] if isinstance(binfo, tuple) else None

    if not add and binfo is None and cver is None:
        return dict(row, state="not adopted", action="skip", reason="no base block and no conventions copy")
    if not add and (newer(bver, std.version) or newer(cver, std.version)):
        return dict(row, state="newer", action="skip",
                    reason="block %s, copy %s, standard %s" % (bver or "-", cver or "-", std.version))

    # The base block.
    block_wanted = not copy_only and not (copy_ignored and binfo is None)
    if block_wanted:
        if binfo == "malformed":
            if not add:
                return dict(row, state="out of date", action="skip",
                            reason="AGENTS.md base block markers are malformed")
            notes.append("AGENTS.md block markers are malformed; left it")
        elif newer(bver, std.version):
            notes.append("AGENTS.md block is newer (%s); left it" % bver)
        elif ag is None:
            row["_writes"][AGENTS] = std.agents_new.encode("utf-8")
        else:
            text, bom, crlf = ag
            new = new_agents_text(text, crlf, binfo, std)
            if new != text:
                row["_writes"][AGENTS] = encode(new, bom)
    elif ag is not None and binfo is None:
        notes.append("AGENTS.md left without the block")

    # The conventions copy.
    if cforeign:
        if not add:
            return dict(row, state="out of date", action="skip",
                        reason="docs/project-conventions.md exists without the standard header")
        notes.append("docs/project-conventions.md exists without the standard header; left it")
    elif newer(cver, std.version):
        notes.append("conventions copy is newer (%s); left it" % cver)
    else:
        crlf = cp[2] if cp else False
        bom = cp[1] if cp else False
        want = std.copy.replace("\n", "\r\n") if crlf else std.copy
        if cp is None or cp[0] != want:
            row["_writes"][COPY] = encode(want, bom)

    writes = row["_writes"]
    row["_commit"] = [p for p in writes if not (in_git and is_ignored(path, p))]
    local = copy_ignored and not row["_commit"]
    if add:
        state = "updated" if writes else "current"
        action = "write " + ", ".join(sorted(writes)) if writes else "none"
        return dict(row, state=state, action=action, reason="; ".join(notes))
    if not writes:
        return dict(row, state="current", reason="local copy, not tracked" if copy_ignored else "")
    if local:
        return dict(row, state="local copy only", action="update",
                    reason="copy is excluded from git; written, never committed")
    skip = skip_reason(path)
    if skip:
        return dict(row, state="out of date", action="skip", reason=skip)
    have = "block %s, copy %s" % (bver or "missing", cver or "missing")
    return dict(row, state="out of date", action="update", reason=have)


def default_branch(path, current):
    remotes = git_ok(path, "remote").split()
    if "origin" not in remotes:
        return current, False
    rc, out, _ = git(path, "symbolic-ref", "-q", "refs/remotes/origin/HEAD")
    if rc == 0 and out.strip():
        return out.strip()[len("refs/remotes/origin/"):], True
    for b in ("main", "master"):
        if git(path, "rev-parse", "-q", "--verify", "refs/remotes/origin/" + b)[0] == 0:
            return b, True
    return None, True


def skip_reason(path):
    gitdir = git_ok(path, "rev-parse", "--absolute-git-dir").strip()
    locks = glob.glob(os.path.join(gitdir, "*.lock"))
    if locks:
        return "git lock file present (%s)" % ", ".join(sorted(os.path.basename(x) for x in locks))
    if git(path, "rev-parse", "-q", "--verify", "HEAD")[0] != 0:
        return "no commits yet"
    rc, out, _ = git(path, "symbolic-ref", "-q", "--short", "HEAD")
    if rc != 0:
        return "detached HEAD"
    current = out.strip()
    default, has_origin = default_branch(path, current)
    if default is None:
        return "cannot tell the default branch (origin has no fetched branches)"
    if current != default:
        return "on branch %s, default is %s" % (current, default)
    if git(path, "diff", "--cached", "--quiet")[0] != 0:
        return "something is already staged"
    st = git_ok(path, "status", "--porcelain", "--untracked-files=all", "--", AGENTS, COPY)
    if st.strip():
        return "uncommitted changes in " + ", ".join(sorted(x[3:] for x in st.split("\n") if x))
    if has_origin and git(path, "rev-parse", "-q", "--verify", "refs/remotes/origin/" + default)[0] == 0:
        n = int(git_ok(path, "rev-list", "--count", "HEAD..refs/remotes/origin/" + default).strip())
        if n:
            return "behind origin/%s by %d" % (default, n)
    return ""


def write(row):
    path = row["path"]
    before = status_lines(path) if row["_git"] else set()
    for rel, data in row["_writes"].items():
        full = os.path.join(path, *rel.split("/"))
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "wb") as f:
            f.write(data)
    if row["_git"]:
        after = status_lines(path)
        changed = {x[3:].strip('"') for x in before ^ after}
        extra = changed - {AGENTS, COPY}
        if extra:
            raise InternalError("unexpected changes after writing: " + ", ".join(sorted(extra)))


def commit(row, std):
    path, paths = row["path"], sorted(row["_commit"])
    msg = MESSAGE.format(v=std.version)
    git_ok(path, "add", "--", *paths)
    rc, _, err = git(path, "commit", "-q", "-m", msg, "--", *paths)
    if rc != 0:
        git(path, "reset", "-q", "--", *paths)
        raise InternalError("commit failed: " + last_line(err))
    files = set(x for x in git_ok(path, "show", "--name-only", "--format=", "HEAD").split("\n") if x)
    if files != set(paths):
        raise InternalError("commit holds unexpected paths: " + ", ".join(sorted(files)))
    return git_ok(path, "rev-parse", "--short", "HEAD").strip()


def push(row, std, sha):
    path = row["path"]
    current = git_ok(path, "symbolic-ref", "--short", "HEAD").strip()
    default, has_origin = default_branch(path, current)
    if not has_origin:
        return dict(row, state="updated", action="committed " + sha, reason="no remote; not pushed")
    rc, _, err = git(path, "push", "-q", "origin", "HEAD:refs/heads/" + default)
    if rc == 0:
        return dict(row, state="updated", action="pushed " + sha, reason="origin/" + default)
    refused = last_line(err)
    branch = "standard/project-guide-" + std.version
    rc, _, err2 = git(path, "push", "-q", "origin", "HEAD:refs/heads/" + branch)
    rc_a, out, _ = git(path, "rev-list", "--count", "refs/remotes/origin/%s..HEAD" % default)
    ahead = out.strip() if rc_a == 0 else "an unknown number of commits"
    if rc != 0:
        return dict(row, state="push failed", action="committed " + sha,
                    reason="%s; branch push failed too: %s; local %s is %s ahead of origin/%s"
                    % (refused, last_line(err2), default, ahead, default))
    return dict(row, state="needs a pull request", action="pushed %s to %s" % (sha, branch),
                reason="origin refused %s; local %s keeps the commit, %s ahead of origin/%s"
                % (default, default, ahead, default))


def discover(root, worktrees_dir):
    skip_top = worktrees_dir.replace("\\", "/").strip("/").split("/")[0]
    found = []
    for entry in sorted(os.listdir(root), key=str.lower):
        full = os.path.join(root, entry)
        if not os.path.isdir(os.path.join(full, ".git")):
            continue  # not a repository, or a linked worktree (its .git is a file)
        found.append((entry, full))
        for child in sorted(os.listdir(full), key=str.lower):
            cfull = os.path.join(full, child)
            if child in (".git", skip_top) or not os.path.isdir(os.path.join(cfull, ".git")):
                continue
            if is_ignored(full, child + "/"):
                found.append((entry + "/" + child, cfull))
    return found


def names(s):
    return set(x.strip() for x in s.split(",") if x.strip()) if s else set()


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--root")
    p.add_argument("--repo")
    p.add_argument("--add", action="store_true")
    p.add_argument("--copy-only", action="store_true",
                   help="with --add: place only the copy (a repo someone else owns)")
    p.add_argument("--worktrees-dir", default=".claude/worktrees")
    p.add_argument("--only", default="")
    p.add_argument("--skip", default="")
    p.add_argument("--apply", action="store_true")
    p.add_argument("--commit", action="store_true")
    p.add_argument("--push", action="store_true")
    p.add_argument("--json", action="store_true")
    a = p.parse_args(argv)
    a.commit = a.commit or a.push
    a.apply = a.apply or a.commit
    if bool(a.root) == bool(a.repo) or bool(a.repo) != a.add:
        p.error("use --root <projects_root>, or --repo <path> --add")

    try:
        std = Standard(a.worktrees_dir)
    except (InternalError, OSError) as e:
        print("error: %s" % e, file=sys.stderr)
        return 2
    rows, failed = [], False
    if a.repo:
        targets = [(os.path.basename(os.path.abspath(a.repo)), os.path.abspath(a.repo))]
    else:
        only, skip = names(a.only), names(a.skip)
        targets = []
        for name, full in discover(os.path.abspath(a.root), a.worktrees_dir):
            if only and name not in only and os.path.basename(full) not in only:
                continue
            if name in skip or os.path.basename(full) in skip:
                rows.append({"name": name, "path": full, "state": "excluded",
                             "action": "skip", "reason": "excluded by --skip"})
                continue
            targets.append((name, full))

    for name, full in targets:
        try:
            row = examine(full, std, add=bool(a.repo), copy_only=a.copy_only)
            if a.repo and row["_writes"]:
                write(row)
            elif a.apply and row["action"] == "update":
                if a.commit and row["_commit"] and "origin" in git_ok(full, "remote").split():
                    rc, _, err = git(full, "fetch", "-q", "origin")
                    if rc != 0:
                        row = dict(row, action="skip", reason="fetch failed: " + last_line(err))
                    else:
                        row = examine(full, std)
                if row["action"] == "update":
                    write(row)
                    if a.commit and row["_commit"]:
                        sha = commit(row, std)
                        if a.push:
                            row = push(row, std, sha)
                        else:
                            row = dict(row, state="updated", action="committed " + sha)
                    else:
                        row = dict(row, state="updated" if row["state"] == "out of date"
                                   else row["state"], action="written, not committed")
        except (InternalError, OSError, UnicodeDecodeError, ValueError) as e:
            failed = True
            row = {"path": full, "state": "error", "action": "none", "reason": str(e)}
        row["name"] = name
        rows.append(row)

    rows.sort(key=lambda r: r["name"].lower())
    clean = [{k: r[k] for k in ("name", "state", "action", "reason")} for r in rows]
    if a.json:
        print(json.dumps({"standard_version": std.version, "repos": clean}, indent=2))
    else:
        print("project-guide standard %s" % std.version)
        cols = ("name", "state", "action", "reason")
        w = [max([len(c)] + [len(r[c]) for r in clean]) for c in cols[:3]]
        print("  ".join(c.ljust(w[i]) for i, c in enumerate(cols[:3])) + "  reason")
        for r in clean:
            print("  ".join(r[c].ljust(w[i]) for i, c in enumerate(cols[:3])) + "  " + r["reason"])
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
